### ISSUE TITLE
Question about pulling notes

### ISSUE THREAD

**Issue by yszhang95** [orgtre/ankiorg#2]
Hello,

It is very nice to have the functionality to pull and push notes. I am a little confused by the behaivor of ankiorg now.

When I pull a note from anki, it seems that `ankiorg` only checks if the notes are modified in deck-level, moving, adding, deleting. I modified a note inside anki and I want to pull the change from anki to org. However, I cannot find anything updated in org file. Did I do anything wrong?

Thanks!

**Comment by nomm-dot** [comment]
I only use this package to export my previously created non-org anki cards to org and then use [anki-editor](https://github.com/anki-editor/anki-editor) to edit them in emacs and sync to anki. I think this is really all this package is intended for. It would be nice for @orgtre or another anki-editor contributor to just integrate it into anki-editor though.

**Comment by orgtre** [comment]
@yszhang95 `ankiorg-pull-notes` should update existing notes in the Org file with the content from Anki. I just fixed a bug that might be related, and trying with the newest version of [anki-editor](https://github.com/anki-editor/anki-editor) I find my existing Org notes updated correctly after modifying their content in Anki and running `ankiorg-pull-notes`. Does your issue still persists?

@Maddogskullcap `ankiorg-pull-notes` together with `anki-editor-push-notes` allows for two-way syncing between your Org file(s) and Anki in a limited sense: When `ankiorg-pull-notes` is run, all Org notes are updated with whatever is in the Anki version of notes with the same note ID. When `anki-editor-push-notes` is run, all Anki notes are updated with whatever is in the Org version of notes with the same note ID. So as long as you don't modify notes in **both** Org and Anki before running a sync, this should allow a two-way sync workflow.

It would be nice to have a per-note-level check of modifications and then sync the last modified version, independent of whether it is in Org or Anki. This has not been successfully implemented yet, mainly because of this [bug](https://github.com/ankitects/anki/issues/2021) in Anki itself, but contributions in this direction are welcome.

Finally, I am open to integrating this into anki-editor, but don't find it very urgent or important.

**Comment by nomm-dot** [comment]
@orgtre Thank you for that useful info! I didn't realize it would update the cards that already exist in the org buffer. 

Additionally, is there a reason this package isn't in the Anki-editor Organization? Wouldn't it maybe inspire Anki-Editor current and future contributors to take a crack at it? They are apart of the same "ecosystem". I guess that's a separate issue though.

I hope to be able to contribute at some point, once I become familiar with elisp.

**Comment by orgtre** [comment]
No real reason, other than that we just only moved anki-editor itself to the organisation. For now I think it's good that development is focused on anki-editor itself.

**Comment by yszhang95** [comment]
@orgtre Thank you so much for the kind reply! I confirm that the issue is resolved.
